name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  hello:

    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello, Workflows!"

  build:

    runs-on: ubuntu-latest
    outputs:
      image_tag: $${{ steps.set-tag.outputs.IMAGE_TAG }}

    steps:
    - uses: actions/checkout@v4

    - name: List repo files
      run: |
        echo "The repository ${{github.repository }} contains the following files:"  
        tree

    - name: Generate Image Tag
      id: set-tag
      run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$IMAGE_TAG

  push:

    runs-on: ubuntu-latest

    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Pull the built image from cache
      run: docker pull my-image-name:${{ needs.build.outputs.image_tag }} || true

    - name: Tag and Push Docker Image
      run: |
        docker tag my-image-name:${{ needs.build.outputs.image_tag }} tshetlerproscia/your-image-name:${{ needs.build.outputs.image_tag }}
        docker tag my-image-name:${{ needs.build.outputs.image_tag }} your-dockerhub-username/your-image-name:latest
        docker push tshetlerproscia/your-image-name:${{ needs.build.outputs.image_tag }}
        docker push tshetlerproscia/your-image-name:latest