name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: 
      - master
  workflow_dispatch:

jobs:

  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, Workflows!"

  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-tag.outputs.IMAGE_TAG }}

    steps:
      - uses: actions/checkout@v4

      - name: List repo files
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree

      - name: Generate Image Tag
        id: set-tag
        run: |
          IMAGE_TAG=$(date +%s)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag hello-world:$IMAGE_TAG

      - name: Save Docker image as an artifact
        run: docker save -o hello-world.tar hello-world:$IMAGE_TAG

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-world-image
          path: hello-world.tar

  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: hello-world-image
          path: .

      - name: Load Docker image
        run: docker load -i hello-world.tar

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Tag and Push Docker Image
        run: |
          docker tag hello-world:${{ needs.build.outputs.image_tag }} tshetlerproscia/hello-world:${{ needs.build.outputs.image_tag }}
          docker tag hello-world:${{ needs.build.outputs.image_tag }} tshetlerproscia/hello-world:latest
          docker push tshetlerproscia/hello-world:${{ needs.build.outputs.image_tag }}
          docker push tshetlerproscia/hello-world:latest
