name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  hello:

    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello, Workflows!"

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: List repo files
      run:  |
        echo "The repository ${{github.repository }} contains the following 
        files:"  
        tree
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
